
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Only used when `DATABASE_URL` is unset (e.g. `prisma generate` in CI). Not a real database. */
const codegenOnlyDatasourceUrl =
  "postgresql://127.0.0.1:5432/__prisma_client_codegen__?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? codegenOnlyDatasourceUrl,
  },
});
